version: "3.8"

name: portfolio

volumes:
  node_modules:
  pnpm_store:

services:
  app:
    image: sambeg/portfolio:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - 3000:3000
      - 6006:6006
    expose:
      - 3000
      - 6006
    volumes:
      - ./:/home/development/app
      - node_modules:/home/development/app/node_modules
      - pnpm_store:/pnpm/store
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://app:3000/api/health | grep -q OK"]
      interval: 5s
      timeout: 3s
      retries: 10
