version: "3.8"

name: portfolio

networks:
  default:
    name: portfolio

services:
  app:
    image: sambeg/portfolio:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - 3000:3000
      - 6006:6006
      - 9339:9339
    expose:
      - 3000
      - 6006
      - 9339
    volumes:
      - ./:/home/development/app
      - ./node_modules:/home/development/app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://app:3000/api/health | grep -q OK"]
      interval: 5s
      timeout: 3s
      retries: 10
